default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: person_os_26_development

test:
  <<: *default
  database: person_os_26_test

production:
  primary: &primary_production
    <<: *default
    database: person_os_26_production
    username: person_os_26
    password: <%= ENV["PERSON_OS_26_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: person_os_26_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: person_os_26_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: person_os_26_production_cable
    migrations_paths: db/cable_migrate
